name: driven
description: Easily copy files and folders to and from Google Drive from your Flutter app.
version: 0.1.4
repository: https://github.com/flutterfromscratch/driven
environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  googleapis: ^11.4.0
  google_sign_in: ^5.4.0
  http: ^1.1.0
  mime: ^1.0.2
  path: ^1.8.1
  crypto: ^3.0.2
  hex: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: null
